removed HA smoke tests that was used by bosh errands and updated subm…
pivotal-cf/cf-redis-smoke-tests pull request #83
Opened 2024-04-16 13:32 UTC by ashrivastav13

This PR includes removal of HA errands test case.

2024-04-17 05:36 UTC, apurvasaraiya requested changes

2024-04-17 05:36 UTC, apurvasaraiya commented on assets/cf-redis-example-app
Do we need submodule changes as part of the PR?

2024-04-17 10:43 UTC, ashrivastav13 commented on assets/cf-redis-example-app
It was raised to check if service gateway pipeline is green or not as there was changes in redis example app.. I will update submodules with latest master merge

2024-04-18 10:55 UTC, apurvasaraiya approved these changes

2024-04-22 08:04 UTC, merged